name: Build Process Monitor

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x86, x64]
        include:
          - platform: x86
            runtime_id: win-x86
          - platform: x64
            runtime_id: win-x64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Verify resources
      run: |
        if (-not (Test-Path "resources/app.ico")) {
            Write-Error "图标文件未找到！当前路径：$pwd"
            Get-ChildItem -Recurse
            exit 1
        }
      shell: powershell

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build
      run: |
        dotnet publish src/ProcessMonitor/ProcessMonitor.csproj `
          -c Release `
          -r ${{ matrix.runtime_id }} `
          --self-contained true `
          /p:PublishSingleFile=true `
          /p:Platform=${{ matrix.platform }} `
          /p:WindowsSDKVersion=10.0.19041.0
      shell: powershell

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ProcessMonitor-${{ matrix.platform }}
        path: src/ProcessMonitor/bin/${{ matrix.platform }}/Release/net8.0-windows/${{ matrix.runtime_id }}/publish/*
