name: Build Process Monitor

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x86, x64]
        include:
          - platform: x86
            runtime_id: win-x86
          - platform: x64
            runtime_id: win-x64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build
      run: |
        # 检查已安装的Windows SDK
        ls 'C:\Program Files (x86)\Windows Kits\10\bin\*\x64\'

        # 使用VS安装器查找SDK
        & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -version 17.0 -products * -requires Microsoft.VisualStudio.Component.Windows10SDK.19041 -property installationPath

        # 构建命令
        dotnet publish src/ProcessMonitor/ProcessMonitor.csproj `
          -c Release `
          -r ${{ matrix.runtime_id }} `
          --self-contained true `
          /p:PublishSingleFile=true `
          /p:Platform=${{ matrix.platform }} `
          /p:WindowsSDKVersion=10.0.19041.0 `
          /p:WindowsTargetPlatformVersion=10.0.19041.0 `
          /p:UseWindowsForms=true
      shell: powershell

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ProcessMonitor-${{ matrix.platform }}
        path: src/ProcessMonitor/bin/${{ matrix.platform }}/Release/net8.0-windows/${{ matrix.runtime_id }}/publish/*
