name: Build Process Monitor

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x86, x64]
        include:
          - platform: x86
            runtime_id: win7-x86
            build_config: Release-Win7-x86
          - platform: x64
            runtime_id: win7-x64
            build_config: Release-Win7-x64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 使用最新checkout版本

    - name: Setup .NET
      uses: actions/setup-dotnet@v4  # 升级到v4版本
      with:
        dotnet-version: 6.0.x

    - name: Build
      run: |
        dotnet publish src/ProcessMonitor/ProcessMonitor.csproj `
          -c ${{ matrix.build_config }} `
          -r ${{ matrix.runtime_id }} `
          --self-contained true `
          /p:PublishSingleFile=true `
          /p:IncludeNativeLibrariesForSelfExtract=true `
          /p:Platform=${{ matrix.platform }}
      shell: powershell

    - name: Upload Artifact
      uses: actions/upload-artifact@v4  # 升级到v4版本
      with:
        name: ProcessMonitor-${{ matrix.platform }}
        path: |
          src/ProcessMonitor/bin/${{ matrix.build_config }}/net6.0-windows/${{ matrix.runtime_id }}/publish/*
        # retention-days参数已废弃，需在仓库设置中配置保留策略
