name: Build All

on:
  push:
    branches:
      - master
jobs:
  build-monitor:
    name: Build Process Monitor
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x86, x64]
        include:
          - platform: x86
            runtime_id: win-x86
          - platform: x64
            runtime_id: win-x64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build Process Monitor
      run: |
        dotnet publish ProcessMonitor/src/ProcessMonitor/ProcessMonitor.csproj `
          -c Release `
          -r ${{ matrix.runtime_id }} `
          --self-contained true `
          /p:PublishSingleFile=true `
          /p:Platform=${{ matrix.platform }} `
          /p:WindowsSDKVersion=10.0.19041.0
      shell: powershell

    - name: Upload Monitor Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ProcessMonitor-${{ matrix.platform }}
        path: ProcessMonitor/src/ProcessMonitor/bin/${{ matrix.platform }}/Release/net8.0-windows/${{ matrix.runtime_id }}/publish/*

  build-validator:
    name: Build PMR Validator
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x86, x64]
        include:
          - platform: x86
            runtime_id: win-x86
          - platform: x64
            runtime_id: win-x64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build Validator
      run: |
        dotnet publish PMRValidator/src/PMRValidator/PMRValidator.csproj `
          -c Release `
          -r ${{ matrix.runtime_id }} `
          --self-contained true `
          /p:PublishSingleFile=true `
          /p:Platform=${{ matrix.platform }} `
          /p:WindowsSDKVersion=10.0.19041.0
      shell: powershell

    - name: Upload Validator Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: PMRValidator-${{ matrix.platform }}
        path: PMRValidator/src/PMRValidator/bin/${{ matrix.platform }}/Release/net8.0-windows/${{ matrix.runtime_id }}/publish/*
