name: Build Process Monitor

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x86, x64]
        include:
          - platform: x86
            runtime_id: win7-x86
            build_config: Release
          - platform: x64
            runtime_id: win7-x64
            build_config: Release

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Build
      run: |
        dotnet publish src/ProcessMonitor/ProcessMonitor.csproj `
          -c ${{ matrix.build_config }} `
          -r ${{ matrix.runtime_id }} `
          --self-contained true `
          /p:PublishSingleFile=true `
          /p:IncludeNativeLibrariesForSelfExtract=true `
          /p:Platform=${{ matrix.platform }}
      shell: powershell

    - name: Verify Output
      run: |
        $pathPattern = "src/ProcessMonitor/bin/${{ matrix.platform }}/${{ matrix.build_config }}/net6.0-windows/${{ matrix.runtime_id }}/publish/*"
        if (-not (Test-Path $pathPattern)) {
          Write-Error "Build output not found at: $pathPattern"
          Get-ChildItem -Recurse -Filter *.dll | % { Write-Host "Found: $($_.FullName)" }
          exit 1
        }
      shell: powershell

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ProcessMonitor-${{ matrix.platform }}
        path: |
          src/ProcessMonitor/bin/${{ matrix.platform }}/${{ matrix.build_config }}/net6.0-windows/${{ matrix.runtime_id }}/publish/*
